# Generated by Django 4.1.3 on 2022-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
